### ISSUE TITLE
佬儿 zhvip.js. 失效了

### ISSUE THREAD

**Issue by cy920820** [WeiGiegie/666#1]

**Comment by WeiGiegie** [comment]
更新了你试试

Cui Yang ***@***.***>于2024年2月21日 周三11:39写道：

**Comment by cy920820** [comment]
佬儿 修复的太快了吧 膜拜

**Comment by WeiGiegie** [comment]
❤️

Cui Yang ***@***.***>于2024年2月21日 周三11:51写道：
